on:
  push:
    tags: ['**']

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: tar -C build -czf build/h5ai-${GITHUB_REF_NAME}.tar.gz _h5ai
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: build/h5ai-*.tar.gz
